apiVersion: v1
kind: Service
metadata:
  name: kuard-loadbalancer
  labels:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    run: kuard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
