apiVersion: v1
kind: Service
metadata:
  name: kuard-nodeport
spec:
  type: NodePort
  selector:
    run: kuard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
